package com.sawan;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class FlatMapTest2 {

	public static void main(String[] args) {
     
	 List<String> loseWeight=new ArrayList<>();
     loseWeight.add("advodados");
     loseWeight.add("beans");
     loseWeight.add("salad");
     loseWeight.add("oats");
     loseWeight.add("broccoli");
	 System.out.println("list data= "+loseWeight);
	 //map()
	  List listofInt=loseWeight.stream().map(s->s.length()).collect(Collectors.toList());
	 System.out.println("list of ints generated by map(): "+listofInt);
	 
	 //flatmap()
	 List<List> listoflistofno=new ArrayList<>();
	 listoflistofno.add(Arrays.asList(2,4));
	 listoflistofno.add(Arrays.asList(3,9));
	 listoflistofno.add(Arrays.asList(4,16));
	 System.out.println("list of ints generated list: "+listoflistofno);
	 
	 List listofInteger=listoflistofno.stream().flatMap(list->list.stream()).collect(Collectors.toList());
	 System.out.println("list of ints generated by flatmap(): "+listofInteger);
	 		
	}
}
